// C:\new-dankkumi\edu-project\src\app\layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ClientWrapper from "@/components/wrapper/ClientWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}

