import type { Metadata } from "next";
import "./globals.css";
import HeaderMenusForDankkumEduProject from "./components/HeaderMenusForDankkumEduProject";

// 동적 import로 SSR 비활성화

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderMenusForDankkumEduProject />
        {children}
      </body>
    </html>
  );
}
